from setuptools import setup

setup(
    name='sfmutils',
    version='2.0.0',
    url='https://github.com/gwu-libraries/sfm-utils',
    author='Social Feed Manager',
    author_email='sfm@gwu.edu',
    packages=['sfmutils'],
    description="Utilities to support Social Feed Manager.",
    platforms=['POSIX'],
    test_suite='tests',
    scripts=['sfmutils/stream_consumer.py', 'sfmutils/find_warcs.py'],
    install_requires=['pytz==2018.5',
                      'requests==2.19.1',
                      'kombu==4.0.2',
                      'librabbitmq==2.0.0',
                      'warcio==1.5.3',
                      'iso8601==0.1.11',
                      'petl==1.1.0',
                      'xlsxwriter==0.9.4'],
    tests_require=['mock==1.3.0',
                   'vcrpy==1.7.4',
                   'python-dateutil==2.4.2'],
    classifiers=[
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Programming Language :: Python :: 3',
        'Development Status :: 4 - Beta',
    ],
)
